routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Authority;
use App\Decree;
use App\Regulation;
use App\Report;
use App\Resolution;
use App\Law;

Route::get('/', function () {
    $autoridades = Authority::all();
    $noticias = Report::all()->take(4);
    return view('welcome',compact('autoridades','noticias'));
});



Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();


Route::view('/admin', 'admin')->name('admin')->middleware('auth');
Route::get('/noticia/admin', 'ReportController@admin')->name('noticia.admin')->middleware('auth');
Route::get('/autoridad/admin', 'AuthorityController@admin')->name('autoridad.admin')->middleware('auth');
Route::get('/decreto/admin', 'DecreeController@admin')->name('decreto.admin')->middleware('auth');
Route::get('/reglamento/admin', 'RegulationController@admin')->name('reglamento.admin')->middleware('auth');
Route::get('/resolucion/admin', 'ResolutionController@admin')->name('resolucion.admin')->middleware('auth');
Route::get('/ley/admin', 'LawController@admin')->name('ley.admin')->middleware('auth');








Route::view('/contacto', 'contacto')->name('contacto');
Route::view('/subsidio', 'subsidio')->name('subsidio');
Route::view('/informacion', 'informacion')->name('informacion');
Route::view('/factura', 'factura')->name('factura');
Route::view('/educa', 'educa')->name('educa');
Route::view('/calidad', 'calidad')->name('calidad');






Route::get('/normativa', function () {
    $decretos = Decree::all();
    $reglamentos = Regulation::all();
    $resoluciones = Resolution::all();
    $leyes = Law::all();
    return view('normativa',compact('leyes','decretos','reglamentos','resoluciones'));
})->name('normativa');



Route::resource('/reclamo', 'ClaimController');
Route::resource('/autoridad', 'AuthorityController');


Route::get('/reglamento/file/{id}', 'RegulationController@getFile')->name('reglamento.file');
Route::resource('/reglamento', 'RegulationController');

Route::resource('/decreto', 'DecreeController');
Route::get('/decreto/file/{id}', 'DecreeController@getFile')->name('decreto.file');


Route::resource('/resolucion', 'ResolutionController');
Route::get('/resolucion/file/{id}', 'ResolutionController@getFile')->name('resolucion.file');


Route::resource('/ley', 'LawController');
Route::get('/ley/file/{id}', 'LawController@getFile')->name('ley.file');


Route::get('/autoridades', 'AuthorityController@get')->name('autoridades');
Route::get('/autoridad/imagen/{id}', 'AuthorityController@getAvatar')->name('image.displayImage');



Route::resource('/noticia', 'ReportController');

Route::get('/noticia/file/{id}', 'ReportController@getFile')->name('noticia.file');

app/Resolution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Resolution extends Model
{
    protected $table = 'resolutions';

    //Atributos que se van a modificar de forma masiva
    protected $fillable = [
        'titulo',
        'archivo',
        'year'
    ];
}

app/Http/Controllers/ResolutionController.php
<?php

namespace App\Http\Controllers;

use App\Resolution;
use Illuminate\Http\Request;

class ResolutionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resolutions = Resolution::all();
        return view('resolutions.index',compact('resolutions'));
    }

    public function admin()
    {

        $resolutions = Resolution::all();
        return view('resolutions.admin',compact('resolutions'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("resolutions.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required',
            'archivo'=>'required',
            'year' => 'required'
        ]);


        $archivo = $request->file('archivo');
        $input['imagename'] = $request->titulo.'.'.$archivo->getClientOriginalExtension();
        $destinationPath =  public_path('res/resoluciones');

        $resolution = new Resolution();

        $resolution->titulo = $request->titulo;
        $resolution->archivo = $resolution->titulo.'.'.$archivo->getClientOriginalExtension();
        $resolution->year = $request->year;

        $resolution->save();

        $archivo->move($destinationPath, $resolution->titulo.'.'.$archivo->getClientOriginalExtension());
        return redirect('resolucion/admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Resolution  $resolution
     * @return \Illuminate\Http\Response
     */
    public function show(Resolution $resolution)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Resolution  $resolution
     * @return \Illuminate\Http\Response
     */
    public function edit(Resolution $resolution)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Resolution  $resolution
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Resolution $resolution)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Resolution  $resolution
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $resolution = Resolution::findOrFail($id);
        $resolution->delete();
        return redirect('resolucion/admin');
    }

    public function getFile($id){

        $resolution = Resolution::findOrFail($id);
        return response()->file(public_path('res/resoluciones/'.$resolution->archivo));
    }
}

resources/views/resolutions/admin.blade.php
@extends('home')
@section('content')

<div class="container">
    <div class="row d-flex justify-content-center">
      <a href="{{route('resolucion.create')}}">Nueva Resolución</a>
        <div class="col d-flex justify-content-center">
            <table class="table table-striped table-responsive text-center ">
                <thead>
            <tr>

                <th scope="col">Título</th>

                <th scope="col">Creado</th>
                <th scope="col">Acción</th>

          </tr>
        </thead>
        <tbody>

            @foreach ($resolutions as $resolution)
            <tr>
                <td> {{$resolution->titulo}}</td>
                <td> {{$resolution->created_at}}</td>






              <td>
                <form action="{{action('ResolutionController@destroy', $resolution->id)}}" method="post">
                  @csrf
                  <input name="_method" type="hidden" value="DELETE">
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </td>

            </tr>



            @endforeach


        </tbody>
      </table>
    </div>
</div>

</div>

<br><br><br>

<br><br><br>
<br><br><br>

@endsection

resources/views/resolutions/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Resoluciones</div>

                <div class="card-body">
                <form method="POST" action="{{route('resolucion.store')}}" aria-label="" enctype="multipart/form-data">
                        @csrf



                        <div class="form-group row">
                            <label for="titulo" class="col-md-4 col-form-label text-md-right">Titulo</label>

                            <div class="col-md-6">
                                <input id="titulo" type="text" class="form-control{{ $errors->has('titulo') ? ' is-invalid' : '' }}" name="titulo" value="{{ old('titulo') }}" required autofocus>

                                @if ($errors->has('titulo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('titulo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="year" name="year" class="col-md-4 col-form-label text-md-right">Año</label>

                            <div class="col-md-6">
                                <input id="year" type="number" class="form-control{{ $errors->has('year') ? ' is-invalid' : '' }}" name="year" value="{{ old('year') }}" required autofocus>

                                @if ($errors->has('year'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('year') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="archivo" class="col-md-4 col-form-label text-md-right">Archivo</label>

                            <div class="col-md-6">
                                <input id="archivo" type="file" class="form-control{{ $errors->has('archivo') ? ' is-invalid' : '' }}" name="archivo" value="{{ old('archivo') }}" required autofocus>

                                @if ($errors->has('archivo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('archivo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Enviar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/resolutions/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row d-flex justify-content-center">
      <a href="{{route('resolucion.create')}}">Nuevo</a>
        <div class="col d-flex justify-content-center">
            <table class="table table-striped table-responsive text-center ">
                <thead>
            <tr>
            
                <th scope="col">Titulo</th>
                <th scope="col">Año</th>
                <th scope="col">Archivo</th>

                <th scope="col">Acción</th>

          </tr>
        </thead>
        <tbody>
            
            @foreach ($resolutions as $resolution)
            <tr>
                
              <td> {{$resolution->titulo}}</td>
              <td> {{$resolution->year}}</td>
              <td><a href="{{route('resolucion.file',$resolution->id)}}">Descargar</a></td>

              
            
              
              
              <td>
                <form action="{{action('ResolutionController@destroy', $resolution->id)}}" method="post">
                  @csrf
                  <input name="_method" type="hidden" value="DELETE">
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </td>

            </tr>
           
            

            @endforeach
          
                
        </tbody>
      </table>
    </div>
</div>

</div>


@endsection