routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Authority;
use App\Decree;
use App\Regulation;
use App\Report;
use App\Resolution;
use App\Law;

Route::get('/', function () {
    $autoridades = Authority::all();
    $noticias = Report::all()->take(4);
    return view('welcome',compact('autoridades','noticias'));
});



Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();


Route::view('/admin', 'admin')->name('admin')->middleware('auth');
Route::get('/noticia/admin', 'ReportController@admin')->name('noticia.admin')->middleware('auth');
Route::get('/autoridad/admin', 'AuthorityController@admin')->name('autoridad.admin')->middleware('auth');
Route::get('/decreto/admin', 'DecreeController@admin')->name('decreto.admin')->middleware('auth');
Route::get('/reglamento/admin', 'RegulationController@admin')->name('reglamento.admin')->middleware('auth');
Route::get('/resolucion/admin', 'ResolutionController@admin')->name('resolucion.admin')->middleware('auth');
Route::get('/ley/admin', 'LawController@admin')->name('ley.admin')->middleware('auth');








Route::view('/contacto', 'contacto')->name('contacto');
Route::view('/subsidio', 'subsidio')->name('subsidio');
Route::view('/informacion', 'informacion')->name('informacion');
Route::view('/factura', 'factura')->name('factura');
Route::view('/educa', 'educa')->name('educa');
Route::view('/calidad', 'calidad')->name('calidad');






Route::get('/normativa', function () {
    $decretos = Decree::all();
    $reglamentos = Regulation::all();
    $resoluciones = Resolution::all();
    $leyes = Law::all();
    return view('normativa',compact('leyes','decretos','reglamentos','resoluciones'));
})->name('normativa');



Route::resource('/reclamo', 'ClaimController');
Route::resource('/autoridad', 'AuthorityController');


Route::get('/reglamento/file/{id}', 'RegulationController@getFile')->name('reglamento.file');
Route::resource('/reglamento', 'RegulationController');

Route::resource('/decreto', 'DecreeController');
Route::get('/decreto/file/{id}', 'DecreeController@getFile')->name('decreto.file');


Route::resource('/resolucion', 'ResolutionController');
Route::get('/resolucion/file/{id}', 'ResolutionController@getFile')->name('resolucion.file');


Route::resource('/ley', 'LawController');
Route::get('/ley/file/{id}', 'LawController@getFile')->name('ley.file');


Route::get('/autoridades', 'AuthorityController@get')->name('autoridades');
Route::get('/autoridad/imagen/{id}', 'AuthorityController@getAvatar')->name('image.displayImage');



Route::resource('/noticia', 'ReportController');

Route::get('/noticia/file/{id}', 'ReportController@getFile')->name('noticia.file');

app/Authority.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Authority extends Model
{
 

    //Atributos que se van a modificar de forma masiva
    protected $fillable = [
        'nombre',
        'cargo',
        'descripcion',
        'foto'
    ];
}

app/Http/Controllers/AuthorityController.php
<?php

namespace App\Http\Controllers;

use Image;



use App\Authority;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
class AuthorityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        /**the authentication middleware here applies to all functions but
         viewForums() and viewForumDetails() and the opposite of this happens
         when you use only()
         */
          //$this->middleware('auth')->except(['get']);
      }

    public function get(){
        $authorities = Authority::all();

        return $authorities;
    }

    public function index()
    {
        
        $authorities = Authority::all();

        return view('authorities.index',compact('authorities'));

    }


    public function admin()
    {
        $authorities = Authority::all();
        return view('authorities.admin',compact('authorities'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        
        return view("authorities.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required|unique:authorities',
            'descripcion'=>'required',
            'cargo'=>'required',
            'foto' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);


        $image = $request->file('foto');
        $input['imagename'] = $request->name.'.'.$image->getClientOriginalExtension();
        $destinationPath =  public_path('img/authorities');
        
        


        $authority = new Authority();

        $authority->nombre = $request->nombre;
        $authority->descripcion = $request->descripcion;
        $authority->cargo = $request->cargo;
        $authority->foto = '.'.$image->getClientOriginalExtension();

        
        $authority->save();

        $image->move($destinationPath, $authority->id.'.'.$image->getClientOriginalExtension());
        return redirect('autoridad/admin');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Authority  $authority
     * @return \Illuminate\Http\Response
     */
    public function show(Authority $authority)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Authority  $authority
     * @return \Illuminate\Http\Response
     */
    public function edit(Authority $authority)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Authority  $authority
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Authority $authority)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Authority  $authority
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $authority = Authority::findOrFail($id);
        $authority->delete();
        
        return redirect('autoridad/admin');
    }

    public function getAvatar($id)
    {
        $report = Authority::findOrFail($id);
        $foto = "".$report->id."".$report->foto;
        return response()->file(public_path('img/authorities/'.$foto));
    }
}

resources/views/authorities/admin.blade.php
@extends('home')
@section('content')

<div class="container">
    <div class="row d-flex justify-content-center">
      <a href="{{route('autoridad.create')}}">Nueva Autoridad</a>
        <div class="col d-flex justify-content-center">
            <table class="table table-striped table-responsive text-center ">
                <thead>
            <tr>
            
                <th scope="col">Cargo</th>
                
                <th scope="col">Nombre</th>
                <th scope="col">Acción</th>

          </tr>
        </thead>
        <tbody>
            
            @foreach ($authorities as $authority)
            <tr>
                <td> {{$authority->cargo}}</td> 
                <td> {{$authority->nombre}}</td>
              

              
            
              
              
              <td>
                <form action="{{action('AuthorityController@destroy', $authority->id)}}" method="post">
                  @csrf
                  <input name="_method" type="hidden" value="DELETE">
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </td>

            </tr>
           
            

            @endforeach
          
                
        </tbody>
      </table>
    </div>
</div>

</div>

<br><br><br>

<br><br><br>
<br><br><br>

@endsection

resources/views/authorities/create.blade.php
@extends('home')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Autoridad</div>

                <div class="card-body">
                <form method="POST" action="{{route('autoridad.store')}}" aria-label="" enctype="multipart/form-data">
                        @csrf

                      

                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre y Apellido</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ old('nombre') }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       
                        <div class="form-group row">
                            <label for="cargo" class="col-md-4 col-form-label text-md-right">Cargo</label>

                            <div class="col-md-6">
                                <input id="cargo" type="text" class="form-control{{ $errors->has('cargo') ? ' is-invalid' : '' }}" name="cargo" value="{{ old('cargo') }}" required autofocus>

                                @if ($errors->has('cargo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('cargo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                       
                        <div class="form-group row">
                            <label for="foto" class="col-md-4 col-form-label text-md-right">Foto</label>

                            <div class="col-md-6">
                                <input id="foto" type="file" class="form-control{{ $errors->has('foto') ? ' is-invalid' : '' }}" name="foto" value="{{ old('foto') }}" required autofocus>

                                @if ($errors->has('foto'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('foto') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
             

                        <div class="form-group row">
                            <label for="descripcion" class="col-md-4 col-form-label text-md-right">Descripcion</label>

                            <div class="col-md-6">
                                <textarea name="descripcion" rows="10" cols="50" class="form-control{{ $errors->has('descripcion') ? ' is-invalid' : '' }}" required></textarea>

                                @if ($errors->has('descripcion'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('descripcion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Enviar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/authorities/delete.blade.php
<div class="modal fade modal-slide-in-right" aria-hidem="true" role="dialog" tabindex="-1" id="modal-delete-{{$authority->id}}">


    <form action="{{action('AuthorityController@destroy', $authority->id)}}" method="post">
          @csrf
      <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="close">
                          <span aria-hidden="true">x</span>
                      </button>
                      <h4 class="modal-tittle">Eliminar Autoridad</h4>
                  </div>
                  <div class="modal-body">
                      <p>Confirme si desea eliminar {{$authority->nombre }}</p>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                      
                      <input name="_method" type="hidden" value="DELETE">
                      <button class="btn btn-danger" type="submit">Delete</button>
                  </div>
              </div>
          </div>

</form>

</div>

resources/views/authorities/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row d-flex justify-content-center">
      <a href="{{route('autoridad.create')}}">Nuevo</a>
        <div class="col d-flex justify-content-center">
            <table class="table table-striped table-responsive text-center ">
                <thead>
            <tr>
            
                <th scope="col">Nombre</th>
                <th scope="col">Cargo</th>
                <th scope="col">Descripcion</th>
                <th scope="col">Foto</th>

                <th scope="col">Acción</th>

          </tr>
        </thead>
        <tbody>
            
            @foreach ($authorities as $authority)
            <tr>
                
              <td> {{$authority->nombre}}</td>
              <td> {{$authority->cargo}}</td>
              <td> {{$authority->descripcion}}</td>
              <td> <img src="{{route('image.displayImage',$authority->id)}}" alt="Imagen no encontrada" width="15%"></td>
            
              
              
              <td>
                <form action="{{action('AuthorityController@destroy', $authority->id)}}" method="post">
                  @csrf
                  <input name="_method" type="hidden" value="DELETE">
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </td>

            </tr>
           
            

            @endforeach
          
                
        </tbody>
      </table>
    </div>
</div>

</div>


@endsection